"""create indicators table

Revision ID: 9ccc73c8c1c9
Revises: 7c3e1a9d5b24
Create Date: 2026-10-03 00:45:42.553595

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "9ccc73c8c1c9"
down_revision: str | Sequence[str] | None = "7c3e1a9d5b24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED')", name="ck_indicators_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_indicators_name"), "indicators", ["name"], unique=False)
    op.create_index(
        op.f("ix_indicators_period"), "indicators", ["period"], unique=False
    )
    op.create_index(
        op.f("ix_indicators_sector"), "indicators", ["sector"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_indicators_sector"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_period"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_name"), table_name="indicators")
    op.drop_table("indicators")
    # ### end Alembic commands ###
